image: docker

stages:
  - test

# services:
# - docker:dind

cache:
  key: ${CI_COMMIT_REF_SLUG}

variables:
  SECRET_KEY: "${SECRET_KEY}"
  DATABASE_URL: postgres://postgres@db:5432/postgres
  DOCKER_DRIVER: overlay2

.docker_compose:
  before_script:
    - apk add --update py-pip gcc
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker info


test:backend:
  extends: .docker_compose
  stage: test
  script:
    - docker-compose run backend pytest
  only:
    - master
