image: docker

stages:
  - test

services:
  - docker:stable-dind

cache:
  key: ${CI_COMMIT_REF_SLUG}

variables:
  # SECRET_KEY: "${SECRET_KEY}"
  SECRET_KEY: "seekrit"
  DATABASE_URL: postgres://postgres@db:5432/postgres
  DOCKER_DRIVER: overlay2

.docker_compose:
  before_script:
    - apk add --update py-pip gcc python-dev build-base libffi-dev openssl-dev libgcc
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker info


test:django:
  extends: .docker_compose
  stage: test
  script:
    # suppress whitenoise warnings
    - docker-compose run django ./manage.py collectstatic
    - docker-compose run django pytest
  only:
    - master
