image: docker

stages:
  - test
  - build
  - deploy

services:
  - docker:stable-dind

cache:
  key: ${CI_COMMIT_REF_SLUG}

variables:
  DOCKER_DRIVER: overlay2
  # AWS KEYS?
  #
  REGISTRY_NAME: registry.gitlab.com/danjac/communikit
  CONTAINER_IMAGE: ${REGISTRY_NAME}:$CI_BUILD_REF_NAME
  HEROKU_APP_NAME: ${HEROKU_APP_NAME}
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  HEROKU_API_KEY: ${HEROKU_API_KEY}

.docker_compose:
  before_script:
    - apk add --update py-pip gcc python-dev build-base libffi-dev openssl-dev libgcc
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker info

test:django:
  extends: .docker_compose
  stage: test
  script:
    - docker-compose run django pytest
  only:
    # - heroku
    - master

build:assets:
  extends: .docker_compose
  stage: build
  artifacts:
    paths:
      - assets
  script:
    - docker-compose run webpack npm run build
    # inject AWS keys into env
    # add in deploy
    # - docker-compose run django ./manage.py collectstatic --file docker-compose.prod.yml
  only:
    # - heroku
    - master

build:django:
  extends: .docker_compose
  stage: build
  script:
    - docker-compose -f docker-compose.prod.yml build django
    - docker-compose -f docker-compose.prod.yml push django
  only:
    # - heroku
    - master

deploy:assets:
  extends: .docker_compose
  stage: deploy
  script:
    - docker-compose run django ./manage.py collectstatic --file docker-compose.prod.yml
  only:
    # - heroku
    - master

deploy:django:
  extends: .docker_compose
  stage: deploy
  script:
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE registry.heroku.com/${HEROKU_APP_NAME}/web
    # - docker-compose -f docker-compose.prod.yml run django sh -c "python manage.py migrate"
    - docker push registry.heroku.com/${HEROKU_APP_NAME}/web
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release django --app ${HEROKU_APP_NAME}/web
  only:
    - heroku
    # - master
