image: docker

stages:
  - test
  - deploy

services:
  - docker:stable-dind

cache:
  key: ${CI_COMMIT_REF_SLUG}

variables:
  DOCKER_DRIVER: overlay2
  # for testing/deployment only
  DATABASE_URL: postgres://postgres@postgres:5432/postgres
  SECRET_KEY: ${SECRET_KEY}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
  REGISTRY_NAME: registry.gitlab.com/danjac/communikit
  CONTAINER_IMAGE: ${REGISTRY_NAME}:$CI_BUILD_REF_NAME
  HEROKU_DEBUG: 1
  HEROKU_APP_NAME: ${HEROKU_APP_NAME}
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  HEROKU_API_KEY: ${HEROKU_API_KEY}

.docker_compose:
  before_script:
    - apk add --update py-pip gcc python-dev build-base libffi-dev openssl-dev libgcc
    - pip install docker-compose
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker info


test:django:
  extends: .docker_compose
  stage: test
  script:
    - docker-compose run django pytest
  only:
    - heroku


deploy:assets:
  extends: .docker_compose
  stage: deploy
  artifacts:
    paths:
      - assets
  script:
    - docker-compose run webpack npm run build
    - docker-compose run -e DJANGO_CONFIGURATION=Production -e DATABASE_URL=${DATABASE_URL} -e DJANGO_SECRET_KEY=${SECRET_KEY} -e DJANGO_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e DJANGO_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e DJANGO_AWS_STORAGE_BUCKET_NAME=${AWS_BUCKET_NAME} django ./manage.py collectstatic --noinput
   only:
    - heroku
