# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.4'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
  REDIS_URL: redis://redis:6379/0

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:11.8
    environment:
      # for testing only!
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  deploy_assets:
    build:
      context: .
      dockerfile: assets.dockerfile
    privileged: true
    volumes:
      - .:/app
      - /app/node_modules

  deploy_django: &django
    build:
      context: .
      dockerfile: django.dockerfile
    privileged: true
    environment: *default-env
    depends_on:
      - postgres
    volumes:
      - .:/app
