version: '3.4'

x-env:
  &default-env
  DATABASE_URL: postgres://postgres@postgres:5432/postgres
  DJANGO_EMAIL_HOST: mailhog
  DJANGO_EMAIL_PORT: 1025
  DJANGO_SECRET_KEY: seekrit
  DJANGO_CELERY_BROKER_URL: redis://redis:6379/0

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: npm run dev
    volumes:
        - .:/app
        - /app/node_modules

  django: &django
    build:
      context: .
    environment: *default-env
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000

  celeryworker:
    <<: *django
    depends_on:
      - postgres
      - mailhog
      - redis
    ports: []
    command: celery -A communikit.celery worker -l INFO

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - mailhog
      - redis
    ports: []
    command: rm -f './celerybeat.pid' && celery -A communikit.celery beat -l INFO

  flower:
    <<: *django
    ports:
      - "5555:5555"
    #environment:
    #- BROKER_URL=redis://redis:6379/0
    command: ['celery', 'flower', '--app=communikit.celery', '--broker="${DJANGO_CELERY_BROKER_URL}"']
