# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.4'

x-env:
  &default-env
  DATABASE_URL: postgres://postgres@postgres:5432/postgres
  DJANGO_SECRET_KEY: seekrit

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
      cache_from:
        - deploy/webpack
    image:
      - deploy/webpack
    volumes:
      - .:/app
      - /app/node_modules

  django: &django
    build:
      context: .
      dockerfile: Dockerfile.local
      cache_from:
        - deploy/webpack
    image:
      - deploy/webpack
    environment: *default-env
    depends_on:
      - postgres
    volumes:
      - .:/app
