version: '3.4'

services:
  web: &django
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    # image: ${REGISTRY_NAME}:${CI_BUILD_REF_NAME}
    image: ${REGISTRY_NAME}:latest
    environment:
      DJANGO_CONFIGURATION: Production
    volumes:
      - .:/app
    command: /start-django

  celeryworker:
    <<: *django
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    ports: []
    command: /start-celerybeat
