# Copyright (c) 2019 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.4'

x-env:
  &default-env
  DATABASE_URL: postgres://postgres@postgres:5432/postgres
  REDIS_URL: redis://redis:6379/0
  DJANGO_EMAIL_HOST: mailhog
  DJANGO_EMAIL_PORT: 1025
  DJANGO_SECRET_KEY: seekrit

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  mailhog:
    image: mailhog/mailhog:v1.0.0
    restart: always
    ports:
      - "8025:8025"

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: npm run dev
    volumes:
        - .:/app
        - /app/node_modules

  django: &django
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: on-failure
    environment: *default-env
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start-django

  celeryworker:
    <<: *django
    depends_on:
      - postgres
      - mailhog
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - mailhog
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    ports:
      - "5555:5555"
    command: /start-flower
