# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.4'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
  REDIS_URL: redis://redis:6379/0
  EMAIL_HOST: mailhog
  EMAIL_PORT: 1025
  # These keys are for development only! Do not copy into a production environment.
  SECRET_KEY: seekrit
  VAPID_PUBLIC_KEY: BJDR4XCoFCYRmCIGcf_1fSCX4CQKFaBzruaoRhhPgVi23MLrxVkeBsgA-WYZdffCesA7DmAfy-gPHHysG3I8R-c
  VAPID_PRIVATE_KEY: vZH9Nz6KMSo8L8ksJFgJyK3vXfU9vIaxZcAcxavKEAk
  VAPID_ADMIN_EMAIL: admin@example.com

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:11.8
    environment:
      # for development only!
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
      - '1025:1025'

  yarn:
    build:
      context: .
      dockerfile: yarn.dockerfile
    privileged: true
    command: yarn dev
    volumes:
      - .:/app
      - /app/node_modules

  django: &django
    build:
      context: .
      dockerfile: local.dockerfile
    restart: on-failure
    privileged: true
    environment: *default-env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    ports:
      - '80:8000'
    command: /start-django

  celeryworker:
    <<: *django
    ports: []
    command: /start-celeryworker
